### ISSUE TITLE
Pre-built binaries

### ISSUE THREAD

**Issue by sharat** [quetzalcoatl/xvsr10#4]
Where can I find pre-built binaries?

**Comment by quetzalcoatl** [comment]
Hmm.. Not good. According to http://stackoverflow.com/questions/13920662/github-where-is-the-download-page-gone and to https://github.com/blog/1302-goodbye-uploads it seems that the 'Downloads' that the GitHub hosted are goind to evaporate. Currently, can still find them here on GitHub, but I don't know how long will they survive there. I'll try to setup some other place, but untill then, please use this the old address: https://github.com/quetzalcoatl/xvsr10/downloads
