### ISSUE TITLE
Project isn't loading with Visual Studio 2010

### ISSUE THREAD

**Issue by sharat** [quetzalcoatl/xvsr10#5]
The forked version of the code isn't loading with Visual Studio 2010. Should I install packages manually?

**Comment by quetzalcoatl** [comment]
Sorry, I don't fully understand. Please provide more details about what exactly you were doing and what were the results.

The code that I last submitted was building properly under VS2010 and after the VSIX was created I could "just install" it, and then the plugin was accessible under "Test" menu as 'xUnit runner manager', where I could configure it and start using.

If you skipped any of those steps ,or if any of them failed, then you might have the feeling that "code isn't being loaded", but, well, "isn't loading" is quite broad term and I hardly can tell you anything more.
